; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.98-52a556a, 2018-05-28)
; on Sun Dec 16 17:48:17 2018
;

HUC	= 1
                                                                           
SMALL	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.data
	.dw $1000
_tile_gfx:
	.inctile "scroll.pcx",4,3
	.code
	.data
	.dw $0
_tile_pal:
	.incpal "scroll.pcx",0
	.code
	.data
	.dw $0
_sprite:
	.incspr "scroll.pcx",64,0,2,1
	.code
	.data
	.dw $0
_sprite_pal:
	.incpal "scroll.pcx",1
	.code
	.data
	.dw $0800
_panel_gfx:
	.incchr "scroll.pcx",0,48,32,4
	.code
	.data
	.dw $0
_panel_pal:
	.incpal "scroll.pcx",2
	.code
	.data
	.dw $0
_panel_bat:
	.incbat "scroll.pcx",8192,0,48,32,4
	.code
	.proc _pause
	__ldwi	0
	  call	_spr_set
	__ldwi	16
	  call	_spr_pal
	__ldwi	16384
	  call	_spr_pattern
	__ldwi	185
	  stx	al
	__ldwi	1
	  call	_spr_ctrl.2
	__ldwi	1
	  call	_spr_pri
	__ldwi	112
	  call	_spr_x
	__ldwi	88
	  call	_spr_y
	  ldy	#0
	  call	_satb_update
LL2:

	  ldy	#0
	  call	_vsync
LL3:

	__ldwi	0
	  call	_joytrg
	__andwi	8
	__notw
	__lbnen	LL2
LL4:

	  ldy	#0
	  call	_spr_hide
	  ldy	#0
	  call	_satb_update
	__ldwi	1
	  call	_clear_joy_events
LL1:

	  rts
	.endp

	.proc _main
	  call	_disp_off
	  call	_cls
	load_sprites	#16384,_sprite,#1
	__ldwi	16
	  stx	al
	__farptr	_sprite_pal,bl,si
	__ldwi	1
	  stx	cl
	  call	_load_palette.3
	__farptr	_demo_map,bl,si
	__ldwi	48
	__stw	ax
	__ldwi	12
	  call	_set_map_data.3
	__farptr	_tile_gfx,bl,si
	__ldwi	12
	__stw	cx
	__farptr	_tile_pal_ref,al,dx
	  call	_set_tile_data.3
	__ldwi	4096
	  call	_load_tile
	__ldwi	0
	  stx	al
	__farptr	_tile_pal,bl,si
	__ldwi	1
	  stx	cl
	  call	_load_palette.3
	__ldwi	0
	  stx	al
	__ldwi	0
	  stx	ah
	__ldwi	0
	__stw	di
	__ldwi	0
	__stw	bx
	__ldwi	17
	  stx	dl
	__ldwi	12
	  stx	dh
	  call	_load_map.6
	__ldwi	1
	  stx	al
	__ldwi	10
	  call	_set_font_color.2
	__ldwi	2
	  call	_set_font_pal
	  call	_load_default_font
	__ldwi	8192
	__stw	di
	__farptr	_panel_gfx,bl,si
	__ldwi	2048
	__stw	cx
	  call	_load_vram.3
	__ldwi	1536
	__stw	di
	__farptr	_panel_bat,bl,si
	__ldwi	32
	  stx	cl
	__ldwi	4
	  stx	ch
	  call	_load_bat.4
	__ldwi	2
	  stx	al
	__farptr	_panel_pal,bl,si
	__ldwi	1
	  stx	cl
	  call	_load_palette.3
	__ldwi	LL0+0
	__stw	si
	__ldwi	1
	  stx	bl
	__ldwi	25
	  call	_put_string.3
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	191
	__pushw
	__ldwi	192
	  call	_scroll
	__ldwi	1
	__pushw
	__ldwi	0
	__pushw
	__ldwi	192
	__pushw
	__ldwi	192
	__pushw
	__ldwi	223
	__pushw
	__ldwi	128
	  call	_scroll
	  call	_disp_on
	__ldwi	0
	  stx	dl
	__ldwi	1
	  stx	al
	__ldwi	8
	  stx	ah
	__farptr	_pause,bl,si
	  call	_set_joy_callback.4
	__ldwi	0
	__stw	_sx
	__ldwi	0
	__stw	_tx
	__ldwi	1
	__stw	_dir
	__ldwi	0
	__stw	_map_x
	__stwi	__main_lend-4, 0
LL6:

LL7:

LL8:

	__ldwi	0
	  call	_joy
	__andwi	128
	__tstw
	__lbeqn	LL10
	__ldwi	-1
	__stw	_dir
	__stwi	__main_lend-2, 1
	__lbra	LL11
LL10:

	__ldwi	0
	  call	_joy
	__andwi	32
	__tstw
	__lbeqn	LL12
	__ldwi	1
	__stw	_dir
	__stwi	__main_lend-2, 1
	__lbran	LL13
LL12:

	__stwi	__main_lend-2, 0
LL13:

LL11:

	__ldw	__main_lend-2
	__cmpwi_eq	1
	__lbeqn	LL14
	__ldw	_sx
	__pushw
	__ldw	_dir
	__aslwi	1
	__addws
	__stw	_tx
	__lbran	LL15
LL14:

	__ldw	_sx
	__addw	_dir
	__stw	_tx
LL15:

	__ldw	_tx
	__andwi	65520
	__pushw
	__ldw	_sx
	__andwi	65520
	  jsr	ne
	__lbeq	LL16
	__ldw	_dir
	__cmpwi_eq	1
	__lbeq	LL17
	incw	_map_x
	__ldw	_map_x
	__stw	<__temp
	__ldwi	48
	  jsr	gtzp
	__lbeqn	LL18
	__ldw	_map_x
	__subwi	48
	__stw	_map_x
LL18:

	__ldw	_tx
	__addwi	256
	__asrwi	4
	  stx	al
	__ldwi	0
	  stx	ah
	__ldw	_map_x
	__addwi	16
	__stw	di
	__ldwi	0
	__stw	bx
	__ldwi	1
	  stx	dl
	__ldwi	12
	  stx	dh
	  call	_load_map.6
	__lbra	LL19
LL17:

	__ldw	_map_x
	__subwi	1
	__stw	_map_x
	__stw	<__temp
	__ldwi	0
	  jsr	ltzp
	__lbeqn	LL20
	__ldw	_map_x
	__addwi	48
	__stw	_map_x
LL20:

	__ldw	_tx
	__asrwi	4
	  stx	al
	__ldwi	0
	  stx	ah
	__ldw	_map_x
	__stw	di
	__ldwi	0
	__stw	bx
	__ldwi	1
	  stx	dl
	__ldwi	12
	  stx	dh
	  call	_load_map.6
LL19:

	incw	__main_lend-4
	__ldw	__main_lend-4
LL16:

	__ldwi	0
	  call	_joy
	__andwi	3
	__notw
	__lbeqn	LL21
	__ldwi	0
	__stw	_sy
	__lbran	LL22
LL21:

	  call	_rand
	__andwi	7
	__stw	_sy
	__ldw	__main_lend-4
	__addw	_sy
	__stw	__main_lend-4
LL22:

	__ldw	__main_lend-4
	__stw	dx
	__ldwi	5
	  stx	cl
	__ldwi	8
	  stx	bl
	__ldwi	25
	  call	_put_number.4
	__ldw	_tx
	__stw	_sx
	__ldwi	0
	__pushw
	__ldw	_sx
	__pushw
	__ldwi	0
	__pushw
	__ldw	_sy
	__pushw
	__ldw	_sy
	__addwi	191
	__pushw
	__ldwi	192
	  call	_scroll
	  ldy	#0
	  call	_vsync
	__lbra	LL8
LL9:

LL5:

	  rts
	.endp
	.data
	.bss
	__main_loc: .ds 4
	__main_lend:
	.code

	.data
	.bank CONST_BANK
LL0:
	.db	115,99,111,114,101,58,32,0
_demo_map:
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	6
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	4
	.db	4
	.db	5
	.db	5
	.db	4
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	6
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	4
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	6
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	4
	.db	5
	.db	4
	.db	5
	.db	4
	.db	4
	.db	4
	.db	5
	.db	4
	.db	4
	.db	4
	.db	5
	.db	5
	.db	4
	.db	5
	.db	6
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	0
	.db	8
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	0
	.db	0
	.db	0
	.db	2
	.db	2
	.db	0
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	6
	.db	5
	.db	7
	.db	7
	.db	7
	.db	7
	.db	0
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	6
	.db	2
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	6
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	5
	.db	8
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	2
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	9
	.db	9
	.db	9
	.db	9
	.db	9
	.db	8
	.db	2
	.db	1
	.db	5
	.db	7
	.db	7
	.db	2
	.db	2
	.db	2
	.db	0
	.db	0
	.db	8
	.db	9
	.db	9
	.db	9
	.db	9
	.db	9
	.db	0
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	0
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	0
	.db	1
	.db	1
	.db	2
	.db	2
	.db	2
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	0
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	0
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	0
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	1
	.db	0
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	3
	.db	0
	.db	1
_tile_pal_ref:
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4
	.db	0<<4

	.bss
_tx:		.ds	2
_sx:		.ds	2
_sy:		.ds	2
_map_x:		.ds	2
_dir:		.ds	2


;0 error(s) in compilation
;	literal pool:8
;	constant pool:588
;	global pool:66
;	Macro pool:94
huc_data:
___huc_data:
huc_data_end:
___huc_data_end:
__heap_start:
	.data
	.bank CONST_BANK
huc_rodata:
___huc_rodata:
huc_rodata_end:
___huc_rodata_end:
