; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.98-52a556a, 2018-05-28)
; on Sun Dec 16 17:35:51 2018
;

HUC	= 1
                                                                           
SMALL	= 1
LINK_st	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.data
	.dw $0
_slider:
	.incspr "slider_vertical_classic.pcx",0,0,1,1
	.code
	.data
	.dw $0
_slider_pal:
	.incpal "slider_vertical_classic.pcx"
	.code
	.data
	.dw $0800
_piano__data__:
	.incchr "three-octave-420.pcx",0,0,52,4
	.code
	.data
	.dw $0
_piano_pal:
	.incpal "three-octave-420.pcx"
	.code
	.proc _init_env
	__stwi	__init_env_lend-3, 8
	__stbi	__init_env_lend-1, 0
LL2:

	__ldub	__init_env_lend-1
	__stw	<__temp
	__ldwi	16
	  jsr	ltzp
	__lbnen	LL4
	__lbra	LL5
LL3:

	__ldub	__init_env_lend-1
	inc	__init_env_lend-1
	__lbra	LL2
LL4:

	__ldub	__init_env_lend-1
	__addwi	1
	  call	_spr_set
	__ldwi	185
	  stx	al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	20992
	  call	_spr_pattern
	__ldw	__init_env_lend-3
	  call	_spr_x
	__ldub	__init_env_lend-1
	__pushw
	__ldwi	31
	__pushw
	__ldub	__init_env_lend-1
	__aslwi	1
	__subws
	  call	_set_env
	__ldwi	1
	  call	_spr_pal
	__ldwi	2
	  call	_spr_pri
	__ldwi	LL0+208
	__stw	si
	__ldw	__init_env_lend-3
	__pushw
	__ldwi	8
	  jsr	udiv
	  stx	bl
	__ldwi	168
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldwi	LL0+212
	__stw	si
	__ldw	__init_env_lend-3
	__pushw
	__ldwi	8
	  jsr	udiv
	  stx	bl
	__ldwi	168
	__pushw
	__ldwi	2
	__aslwi	5
	__subws
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldw	__init_env_lend-3
	__addwi	16
	__stw	__init_env_lend-3
	__lbra	LL3
LL5:

	__ldwi	1
	  call	_set_font_pal
	__ldwi	LL0+216
	__stw	si
	__ldwi	16
	__aslwi	4
	__addwi	8
	__subwi	8
	__pushw
	__ldwi	2
	  jsr	sdiv
	__pushw
	__ldwi	8
	  jsr	sdiv
	__subwi	4
	  stx	bl
	__ldwi	168
	__pushw
	__ldwi	2
	__aslwi	3
	__subws
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldwi	0
	  call	_set_font_pal
LL1:

	  rts
	.endp
	.data
	.bss
	__init_env_loc: .ds 3
	__init_env_lend:
	.code

	.proc _set_env
	__pushw
	__ldub_s	0
	__stw	dx
	__ldwi	2
	  stx	cl
	__ldub_s	2
	__aslwi	4
	__addwi	8
	__pushw
	__ldwi	8
	  jsr	sdiv
	  stx	bl
	__ldwi	168
	__pushw
	__ldwi	8
	  jsr	sdiv
	__addwi	1
	  call	_put_number.4
	__ldwi	_env
	__addub_s	2
	__stw	<__ptr
	__ldub_s	0
	__stbp	__ptr
	__ldub_s	2
	__addwi	1
	  call	_spr_set
	__ldwi	160
	__pushw
	__ldub_s	2
	__aslwi	1
	__subws
	  call	_spr_y
LL6:

	__addmi	4,__stack
	  rts
	.endp

	.proc _set_wave
	__pushw
	__ldub_s	0
	__stw	dx
	__ldwi	2
	  stx	cl
	__ldub_s	2
	__mulwi	12
	__addwi	8
	__pushw
	__ldwi	8
	  jsr	sdiv
	  stx	bl
	__ldwi	80
	__pushw
	__ldwi	8
	  jsr	sdiv
	__addwi	1
	__pushw
	__ldub_s	4
	__andwi	1
	__addws
	  call	_put_number.4
	__ldwi	_wave
	__addub_s	2
	__stw	<__ptr
	__ldub_s	0
	__stbp	__ptr
	__ldub_s	2
	__addwi	17
	  call	_spr_set
	__ldwi	72
	__pushw
	__ldub_s	2
	__aslwi	1
	__subws
	  call	_spr_y
LL7:

	__addmi	4,__stack
	  rts
	.endp

	.proc _init_wave
	__stwi	__init_wave_lend-3, 8
	__stbi	__init_wave_lend-1, 0
LL9:

	__ldub	__init_wave_lend-1
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
	__lbnen	LL11
	__lbra	LL12
LL10:

	__ldub	__init_wave_lend-1
	inc	__init_wave_lend-1
	__lbra	LL9
LL11:

	__ldub	__init_wave_lend-1
	__addwi	17
	  call	_spr_set
	__ldwi	185
	  stx	al
	__ldwi	0
	  call	_spr_ctrl.2
	__ldwi	20992
	  call	_spr_pattern
	__ldw	__init_wave_lend-3
	  call	_spr_x
	__ldub	__init_wave_lend-1
	__pushw
	__ldub	__init_wave_lend-1
	__stw	<__temp
	__ldwi	16
	  jsr	gezp
	__lbeqn	LL13
	__ldwi	31
	__lbran	LL14
LL13:

	__ldwi	0
LL14:

	  call	_set_wave
	__ldwi	1
	  call	_spr_pal
	__ldwi	2
	  call	_spr_pri
	__ldwi	LL0+225
	__stw	si
	__ldw	__init_wave_lend-3
	__pushw
	__ldwi	8
	  jsr	udiv
	  stx	bl
	__ldwi	80
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldwi	LL0+228
	__stw	si
	__ldw	__init_wave_lend-3
	__pushw
	__ldwi	8
	  jsr	udiv
	  stx	bl
	__ldwi	80
	__pushw
	__ldwi	2
	__aslwi	5
	__subws
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldw	__init_wave_lend-3
	__addwi	12
	__stw	__init_wave_lend-3
	__lbra	LL10
LL12:

	__ldwi	1
	  call	_set_font_pal
	__ldwi	LL0+231
	__stw	si
	__ldwi	12
	__aslwi	5
	__addwi	8
	__subwi	8
	__pushw
	__ldwi	2
	  jsr	sdiv
	__pushw
	__ldwi	8
	  jsr	sdiv
	__subwi	4
	  stx	bl
	__ldwi	80
	__pushw
	__ldwi	2
	__aslwi	4
	__subws
	__pushw
	__ldwi	8
	  jsr	sdiv
	  call	_put_string.3
	__ldwi	0
	  call	_set_font_pal
LL8:

	  rts
	.endp
	.data
	.bss
	__init_wave_loc: .ds 3
	__init_wave_lend:
	.code

	.proc _init_piano
	__ldwi	8
	  stx	al
	__farptr	_piano_pal,bl,si
	__ldwi	1
	  stx	cl
	  call	_load_palette.3
	__ldwi	_piano
	__stw	di
	  call	_set_tile_data.1
	__ldwi	4096
	  call	_load_tile
	__stwi	__init_piano_lend-2, 0
LL16:

	__ldw	__init_piano_lend-2
	__pushw
	__ldwi	52
	__aslwi	2
	  jsr	ult
	__lbnen	LL18
	__lbra	LL19
LL17:

	__ldw	__init_piano_lend-2
	incw	__init_piano_lend-2
	__lbra	LL16
LL18:

	__ldwi	_piano_map
	__addw	__init_piano_lend-2
	__stw	<__ptr
	__ldw	__init_piano_lend-2
	__stbp	__ptr
	__lbra	LL17
LL19:

	__farptr	_piano_map,bl,si
	__ldwi	52
	__stw	ax
	__ldwi	4
	  call	_set_map_data.3
	__ldwi	512
	__pushw
	__ldwi	2
	  jsr	sdiv
	__pushw
	__ldwi	8
	  jsr	sdiv
	__subwi	26
	  stx	al
	__ldwi	24
	  stx	ah
	__ldwi	0
	__stw	di
	__ldwi	0
	__stw	bx
	__ldwi	52
	  stx	dl
	__ldwi	4
	  stx	dh
	  call	_load_map.6
LL15:

	  rts
	.endp
	.data
	.bss
	__init_piano_loc: .ds 6
	__init_piano_lend:
	.code

