; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.98-52a556a, 2018-05-28)
; on Sun Dec 16 17:34:52 2018
;

HUC	= 1
                                                                           
_AC = 1
_SGX = 1
SMALL	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.data
	.dw $0
_map:
	.incbin "pce_bat1.bin"

	.code
	.data
	.dw $0
_tile:
	.incbin "pce_tile1.bin"

	.code
	.data
	.dw $0
_pal:
	.incbin "pce_pal1.bin"

	.code
	.proc _main
	  call	_disp_off
	  call	_spr_set
	  ldy	#0
	  call	_spr_hide
	  call	_load_default_font
	__ldwi	0
	  call	_set_screen_size
	  call	_disp_on
	  call	_sgx_detect
	__notw
	__lbeq	LL2
	__ldwi	LL0+0
	__stw	si
	__ldwi	2
	  stx	bl
	__ldwi	13
	  call	_put_string.3
LL3:

LL4:

LL5:

	__lbran	LL5
LL6:

LL2:

	__ldwi	0
	  stx	al
	__ldwi	511
	__stw	bx
	  call	_vpc_win_size.2
	__ldwi	1
	  stx	al
	__ldwi	511
	__stw	bx
	  call	_vpc_win_size.2
	__ldwi	0
	  stx	al
	__ldwi	3
	  stx	bl
	  call	_vpc_win_reg.2
	__ldwi	1
	  stx	al
	__ldwi	3
	  stx	bl
	  call	_vpc_win_reg.2
	__ldwi	2
	  stx	al
	__ldwi	3
	  stx	bl
	  call	_vpc_win_reg.2
	__ldwi	3
	  stx	al
	__ldwi	3
	  stx	bl
	  call	_vpc_win_reg.2
	__ldwi	4
	  call	_set_font_pal
	__ldwi	14
	  stx	al
	__ldwi	0
	  call	_set_font_color.2
	  call	_load_default_font
	__ldwi	LL0+29
	__stw	si
	__ldwi	2
	  stx	bl
	__ldwi	3
	  call	_put_string.3
	__ldwi	0
	  call	_sgx_set_screen_size.1
	__ldwi	0
	__stw	di
	__farptr	_map,bl,si
	__ldwi	1024
	__stw	cx
	  call	_sgx_load_vram.3
	__ldwi	4096
	__stw	di
	__farptr	_tile,bl,si
	__ldwi	16384
	__stw	cx
	  call	_sgx_load_vram.3
	__ldwi	0
	  stx	al
	__farptr	_pal,bl,si
	__ldwi	16
	  stx	cl
	  call	_load_palette.3
	  call	_sgx_spr_hide
	__ldwi	1
	  call	_sgx_spr_set.1
	  call	_sgx_disp_on
	__ldwi	LL0+48
	__stw	si
	__ldwi	2
	  stx	bl
	__ldwi	4
	  call	_put_string.3
	  call	_ac_init
	__tstw
	__lbeq	LL7
	__ldwi	LL0+62
	__stw	si
	__ldwi	15
	  stx	bl
	__ldwi	4
	  call	_put_string.3
	__ldwi	0
	  stx	ac_reg_1_high
	__ldwi	0
	__stw	ac_reg_1_low
	__ldwi	0
	__stw	ac_reg_1_offset_l
	__ldwi	1
	__stw	ac_reg_1_incrmt_l
	__ldwi	17
	  stx	ac_reg_1_control
	__ldwi	LL0+72
	__stw	si
	__ldwi	2
	  stx	bl
	__ldwi	5
	  call	_put_string.3
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	450
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	454
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	458
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	462
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	466
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	470
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	474
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	0
	  stx	bl
	__ldwi	0
	  stx	cl
	__ldwi	478
	__stw	dx
	__ldwi	4
	  stx	al
	  call	_ac_cd_xfer.4
	__ldwi	LL0+88
	__stw	si
	__ldwi	17
	  stx	bl
	__ldwi	5
	  call	_put_string.3
	  call	_sgx_bg_on
	__ldwi	0
	  stx	ac_reg_1_high
	__ldwi	0
	__stw	ac_reg_1_low
	__ldwi	0
	  stx	al
	__ldwi	4096
	__stw	bx
	__ldwi	15360
	__stw	cx
	__ldwi	1
	  stx	ah
	  call	_ac_vram_dma.4
	__ldwi	0
	  stx	ac_reg_1_high
	__ldwi	32768
	__stw	ac_reg_1_low
	__ldwi	0
	  stx	al
	__ldwi	0
	__stw	bx
	__ldwi	2048
	__stw	cx
	__ldwi	1
	  stx	ah
	  call	_ac_vram_dma.4
	__ldwi	0
	  stx	ac_reg_1_high
	__ldwi	34816
	__stw	ac_reg_1_low
	__ldwi	0
	  stx	al
	__ldwi	0
	__stw	bx
	__ldwi	256
	__stw	cx
	  call	_ac_vce_copy.3
	__ldwi	60
	  ldy	#1
	  call	_vsync
	__ldwi	60
	  ldy	#1
	  call	_vsync
	__lbra	LL8
LL7:

	__ldwi	LL0+98
	__stw	si
	__ldwi	15
	  stx	bl
	__ldwi	4
	  call	_put_string.3
LL9:

LL10:

LL11:

	__lbran	LL11
LL12:

LL8:

	__ldwi	LL0+112
	__stw	si
	__ldwi	2
	  stx	bl
	__ldwi	6
	  call	_put_string.3
LL13:

LL14:

LL15:

	__stbi	__main_lend-2, 0
LL17:

	__ldb	__main_lend-2
	__stw	<__temp
	__ldwi	255
	  jsr	ltzp
	__lbnen	LL19
	__lbra	LL20
LL18:

	__ldwi	__main_lend-2
	__addbi_p	1
	__subwi	1
	__lbra	LL17
LL19:

	  ldy	#0
	  call	_vsync
	__ldb	__main_lend-2
	__stw	ax
	__ldb	__main_lend-2
	__stw	bx
	  call	_sgx_scroll.2
	__lbra	LL18
LL20:

	__lbra	LL15
LL16:

LL1:

	  rts
	.endp
	.data
	.bss
	__main_loc: .ds 6
	__main_lend:
	.code

	.data
	.bank CONST_BANK
LL0:
	.db	72,97,108,116,58,32,83,71
	.db	88,32,110,111,116,32,104,97
	.db	114,100,119,97,114,101,32,102
	.db	111,117,110,100,0,83,71,88
	.db	32,104,97,114,100,119,97,114
	.db	101,32,102,111,117,110,100,0
	.db	65,114,99,97,100,101,32,67
	.db	97,114,100,58,32,0,100,101
	.db	116,101,99,116,101,100,46,0
	.db	67,68,45,62,65,67,32,120
	.db	102,101,114,46,46,46,32,0
	.db	102,105,110,105,115,104,101,100
	.db	46,0,110,111,116,32,100,101
	.db	116,101,99,116,101,100,46,0
	.db	83,99,114,111,108,108,105,110
	.db	103,32,83,71,88,32,108,97
	.db	121,101,114,32,0

	.bss

;0 error(s) in compilation
;	literal pool:133
;	constant pool:0
;	global pool:78
;	Macro pool:111
huc_data:
___huc_data:
huc_data_end:
___huc_data_end:
__heap_start:
	.data
	.bank CONST_BANK
huc_rodata:
___huc_rodata:
huc_rodata_end:
___huc_rodata_end:
